name: Update Starred Repos
on:
  schedule:
   #- cron: "0 19 * * *" # 12 PM Nepal time is 6 AM UTC
   - cron: "0 */2 * * *" # Every 2 Hr
  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:
#------------------------------------------------------------------------------------#
env:
  USER_AGENT: "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/115.0"
  RCLONE_CF_R2_PUB: "${{ secrets.RCLONE_CF_R2_PUB }}"
  GITHUB_TOKEN: "${{ secrets.GHP_NO_PRIVILEGE }}"
#------------------------------------------------------------------------------------#
jobs:
  awesome-stars:
    name: Update Starred Repos
    runs-on: ubuntu-latest
    permissions:
      contents: write
    container: ghcr.io/juev/starred:latest
    steps:
      - name: 🚀 Run Starred
        run: |
          # Presets
          set -x ; set +e
          #--------------#        
          starred --username azathothas --repository Stars --sort --token ${GITHUB_TOKEN} --message '💫'
        continue-on-error: true          
#------------------------------------------------------------------------------------#
  BackUp:
    needs: [awesome-stars]
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: main
          filter: "blob:none"

      - name: Setup Env
        run: |
          sudo apt update -y
          sudo apt install dos2unix -y
          pip install ansi2txt --upgrade
        continue-on-error: true

      - name: Install Addons
        run: |
          # Presets
          set -x ; set +e
          #--------------#
          #action-lint
          sudo curl -qfsSL "https://bin.ajam.dev/x86_64_Linux/actionlint" -o "/usr/local/bin/actionlint" && sudo chmod +xwr "/usr/local/bin/actionlint"
          #delta
          sudo curl -qfsSL "https://bin.ajam.dev/x86_64_Linux/delta" -o "/usr/local/bin/delta" && sudo chmod +xwr "/usr/local/bin/delta"
          #dust
          sudo curl -qfsSL "https://bin.ajam.dev/x86_64_Linux/dust" -o "/usr/local/bin/dust" && sudo chmod +xwr "/usr/local/bin/dust"
          #eget
          sudo curl -qfsSL "https://bin.ajam.dev/x86_64_Linux/eget" -o "/usr/local/bin/eget" && sudo chmod +xwr "/usr/local/bin/eget"
          #git-sizer
          sudo curl -qfsSL "https://bin.ajam.dev/x86_64_Linux/git-sizer" -o "/usr/local/bin/git-sizer" && sudo chmod +xwr "/usr/local/bin/git-sizer"
          #rclone
          sudo curl -qfsSL "https://bin.ajam.dev/x86_64_Linux/rclone" -o "/usr/local/bin/rclone" && sudo chmod +xwr "/usr/local/bin/rclone"
          #validtoml
          sudo curl -qfsSL "https://bin.ajam.dev/x86_64_Linux/validtoml" -o "/usr/local/bin/validtoml" && sudo chmod +xwr "/usr/local/bin/validtoml"
          #Yq
          sudo curl -qfsSL "https://bin.ajam.dev/x86_64_Linux/yq" -o "/usr/local/bin/yq" && sudo chmod +xwr "/usr/local/bin/yq"
          #Yj
          sudo curl -qfsSL "https://bin.ajam.dev/x86_64_Linux/yj" -o "/usr/local/bin/yj" && sudo chmod +xwr "/usr/local/bin/yj"
        continue-on-error: true
#------------------------------------------------------------------------------------#        
      - name: rClone BackUp Repo ("https://pub.ajam.dev/repos/$GITHUB_REPOSITORY")
        run: |
          # Presets
          set -x ; set +e
          #--------------#
          #touch "$HOME/.rclone.conf"
          echo "${{ secrets.RCLONE_CF_R2_PUB }}" > "$HOME/.rclone.conf"
          #chdir to Repo
          cd "$GITHUB_WORKSPACE/main"
          #Git pull
          git pull origin main --no-edit 2>/dev/null
          #Del Bloat
          rm -rf "$(pwd)/.git"
          #Upload to Pub
          echo -e "[+] Syncing $GITHUB_REPOSITORY to pub.ajam.dev/repos/$GITHUB_REPOSITORY \n"
          rclone sync "." "r2:/pub/repos/$GITHUB_REPOSITORY/" --progress --check-first
        continue-on-error: true
#EOF
#------------------------------------------------------------------------------------#
